repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: local
    hooks:
    - id: pylint
      name: pylint
      language: system
      entry: pylint
      require_serial: true
      types:
      - python
  - repo: https://github.com/crate-ci/typos
    rev: v1.3.3
    hooks:
      - id: typos
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.2
    hooks:
      - id: python-safety-dependencies-check
